name: Check Label
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - main
      - stage_v2
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - id: label
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: 'bug'
          exit_type: success
  bevalidation:
    runs-on: ubuntu-lates
    needs: label
    if: needs.label.output == 'success'
    steps:
      - run: exit 0
