name: Check Label
on:
  pull_request:
    branches:
      - main
      - stage_v2
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: 'bug'
