name: 'Cache Test'
on:
  pull_request:
    branches:
      - main

jobs:
  test-job:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: '18.10.0'
      - name: 'Install dependencies'
        run: npm ci
      - name: 'Build'
        run: npm run build