name: 'Cache Test'
on:
  pull_request:
    branches:
      - main
      - stage_v2

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: '18.10.0'
      - name: Restore node_modules cache
        id: cache-npm
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            ~/.cache
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: 'Install dependencies'
        run: npm ci
      - name: 'Build'
        run: npm run build
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: npm run cypress
          wait-on: 'http://localhost:3388'
          config: baseUrl=http://localhost:3388
